# Generated by Django 3.2 on 2021-08-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50)),
                ('PostName', models.CharField(max_length=50)),
                ('content', models.TextField(default=None)),
                ('video', models.FileField(upload_to='Post/video')),
            ],
        ),
    ]
