# Generated by Django 3.2 on 2021-08-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='PostName',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Category',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
