# Generated by Django 3.2 on 2021-08-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20210822_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='video',
            field=models.FileField(default=None, upload_to='Post/video'),
        ),
    ]
