# Generated by Django 3.2 on 2021-10-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_blogpost_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='video',
        ),
    ]
