# Generated by Django 3.2 on 2021-10-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_remove_blogpost_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img1',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
