# Generated by Django 3.2.9 on 2021-12-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20211227_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default=None, max_length=50)),
                ('Suggestions', models.TextField(default=None)),
            ],
        ),
    ]
